# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8aab04f2bb72e6180f0a40c50172437e45236ee7c8f73aa292ebd4aa5924fa3e3a9878456d59681685727e7397c1148b9a8e4b383f3d1c8c44523dbe3b36635

test:
  secret_key_base: 3b58639c858fe9840efac45c8ac6c496928c2b30aa0b93d122303f3497479c2d7c8256349f8c7df5fa368efbc83624dd9bfd3f49a2359709c056da3a349ba131

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
